name: release
on:
  push:
    tags:
      - 'v*'
  workflow_call:
    inputs:
      go:
        description: 'Go version'
        default: 1.18 # auto-update/latest-go-version
        required: false
        type: string

jobs:
  release:
    permissions:
        contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go }}
    - name: Build and release
      uses: goreleaser/goreleaser-action@v3
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
