# SPDX-FileCopyrightText: 2023 The Pion community <https://pion.ly>
# SPDX-License-Identifier: MIT

name: Go Fuzz (reusable)
on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: "stable"
      fuzz-time:
        required: false
        type: string
        default: "60s"

permissions:
  contents: read

jobs:
  fuzz:
    runs-on: ubuntu-24.04
    timeout-minutes: 120

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ inputs.go-version }}

      - name: Cache Go build/module cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install GNU Parallel
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y parallel

      - name: Run all fuzz targets (${{ inputs.fuzz-time }} each) in parallel
        shell: bash
        run: |
          set -euo pipefail

          targets_file=$(mktemp)
          for pkg in $(go list ./...); do
            for t in $(go test "$pkg" -list '^Fuzz' | grep '^Fuzz' || true); do
              echo "$pkg $t"
            done
          done > "$targets_file"

          if [ ! -s "$targets_file" ]; then
            echo "No fuzz targets found"
            rm "$targets_file"
            exit 0
          fi

          echo "Found $(wc -l < "$targets_file") fuzz target(s)"

          parallel --colsep ' ' -j 4 --joblog fuzz-parallel.log --line-buffer \
            'echo "::group::Fuzzing {1}/{2}"; go test -run=^$ -fuzz={2} -fuzztime=${{ inputs.fuzz-time }} {1}; echo "::endgroup::"' \
            :::: "$targets_file"

          rm "$targets_file"

          echo "Parallel execution summary:"
          cat fuzz-parallel.log

      - name: Upload fuzz artifacts
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: fuzz-artifacts
          path: "**/testdata/fuzz/**"
          if-no-files-found: ignore
