# SPDX-FileCopyrightText: 2023 The Pion community <https://pion.ly>
# SPDX-License-Identifier: MIT

name: Generate Authors

on:
  pull_request:

jobs:
  generate-authors:
    name: Generate Authors
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate the authors file
        run: scripts/generate-authors.sh

      - name: Add the authors file to git
        run: git add AUTHORS.txt

      - name: Get last commit author
        id: last-commit-author
        run: echo "msg=$(git log -1 --pretty='%aN <%ae>')" >> ${GITHUB_OUTPUT}

      - name: Check if AUTHORS.txt file has changed
        id: git-status-output
        run: echo "msg=$(git status -s | wc -l)" >> ${GITHUB_OUTPUT}

      - name: Commit and push
        if: ${{ steps.git-status-output.outputs.msg != '0' }}
        run: |
          git config user.email $(echo "${{ steps.last-commit-author.outputs.msg }}" | sed 's/\(.\+\) <\(\S\+\)>/\2/')
          git config user.name $(echo "${{ steps.last-commit-author.outputs.msg }}" | sed 's/\(.\+\) <\(\S\+\)>/\1/')
          git add AUTHORS.txt
          git commit -m "Update AUTHORS.txt"
          git push ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} $(git symbolic-ref -q --short HEAD)
